export const CART_ADD_ITEM_FAIL: string = 'CART_ADD_ITEM_FAIL';
export const CART_ADD_ITEM: string = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM: string = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS: string = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD: string = 'CART_SAVE_PAYMENT_METHOD';